# Generated by Django 6.0.1 on 2026-02-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
